### PR TITLE
Deal with multiple image hashes.

### PR DESCRIPTION
**Pull request by bjlittle**

### CODE REVIEW

**Comment by marqh** [comment]
@bjlittle it would be great to have one example of having two hashes for one test in the collection, to see this behaviour in action and test the test resource test

cheers
mark

**Comment by bjlittle** [comment]
@marqh Targeted the failing test `iris.tests.test_analysis.TestRotatedPole.test_all.2` which had the original hash `https://scitools.github.io/test-images-scitools/image_files/0f5c99da44a0f4640374961907f324a5dac767eb.png`

Added the new and additional hash `https://scitools.github.io/test-images-scitools/image_files/6b5e42fc27c146b1e5e6b6e57b7d4dce0891463b.png`

This new resource *has not been added* to the `test-images-scitools` repo, which should exercise your new test ...

**Comment by bjlittle** [comment]
@marqh ping ...

**Comment by marqh** [comment]
ok, this is looking good, a couple of minor issues with py3 which i'm fixing now

merging....

**Pull request merged**
